#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

i=1
x=0
echo "Hour: $x"
while [ $x -le 12 ];
do
    if [ $i -eq 60 ];then
        x=$((1 + x))
        echo "Hour: $x"
        i=1
    fi
    echo "$i"
    i=$((i + 1))
done
